[build]
  command = "node build.js"
  publish = "."

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production]
  command = "node build.js"

[context.deploy-preview]
  command = "node build.js"
